/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#00714e",
        "on-secondary-fixed-variant": "#005137",
        "on-primary-fixed": "#002113",
        "surface-container-high": "#e1e8fd",
        "on-primary-container": "#00422b",
        "primary-fixed": "#6ffbbe",
        "on-secondary-fixed": "#002114",
        "tertiary": "#416656",
        "n100-surface": "#F3F4F6",
        "secondary-fixed-dim": "#68dba9",
        "on-surface-variant": "#3c4a42",
        "outline": "#6c7a71",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#006c49",
        "tertiary-container": "#84ab98",
        "primary-fixed-dim": "#4edea3",
        "primary-container": "#10b981",
        "primary": "#006c49",
        "n400-inactive": "#9CA3AF",
        "n600-secondary-text": "#4B5563",
        "tertiary-fixed-dim": "#a8cfbc",
        "secondary-fixed": "#85f8c4",
        "inverse-on-surface": "#edf0ff",
        "on-tertiary-container": "#1b3f31",
        "on-tertiary-fixed-variant": "#294e3f",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#002115",
        "warning-amber": "#F59E0B",
        "secondary-container": "#82f5c1",
        "error": "#ba1a1a",
        "surface-container-low": "#f1f3ff",
        "background": "#f9f9ff",
        "inverse-primary": "#4edea3",
        "on-background": "#141b2b",
        "outline-variant": "#bbcabf",
        "tertiary-fixed": "#c3ecd7",
        "on-surface": "#141b2b",
        "surface-variant": "#dce2f7",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "surface-container": "#e9edff",
        "secondary": "#006c4a",
        "error-container": "#ffdad6",
        "surface-container-highest": "#dce2f7",
        "inverse-surface": "#293040",
        "surface": "#f9f9ff",
        "surface-dim": "#d3daef",
        "n300-border": "#D1D5DB",
        "surface-bright": "#f9f9ff",
        "error-ruby": "#EF4444",
        "on-primary-fixed-variant": "#005236",
        "on-secondary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "16px",
        "layout-max-width": "430px",
        "xs": "4px",
        "base": "4px",
        "md": "12px",
        "xl": "20px",
        "sm": "8px",
        "xxl": "24px",
        "nav-height": "64px"
      },
      fontFamily: {
        "nav-label": ["Plus Jakarta Sans", "sans-serif"],
        "body-regular": ["Plus Jakarta Sans", "sans-serif"],
        "heading-2": ["Plus Jakarta Sans", "sans-serif"],
        "heading-1": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-button": ["Plus Jakarta Sans", "sans-serif"],
        "caption": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "nav-label": ["10px", {"lineHeight": "14px", "letterSpacing": "0px", "fontWeight": "400"}],
        "body-regular": ["14px", {"lineHeight": "22px", "letterSpacing": "0px", "fontWeight": "400"}],
        "heading-2": ["18px", {"lineHeight": "26px", "letterSpacing": "0px", "fontWeight": "600"}],
        "heading-1": ["24px", {"lineHeight": "32px", "letterSpacing": "0px", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "letterSpacing": "0px", "fontWeight": "500"}],
        "label-button": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1px", "fontWeight": "600"}],
        "caption": ["12px", {"lineHeight": "18px", "letterSpacing": "0px", "fontWeight": "400"}],
        "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.5px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
